targets:
  $default:
    sources:
      - web_api/**
      - lib/**
      - web/**
      - pubspec.*
      - $package$
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
            - -O4 
            - --csp
        generate_for:
          - web_api/**.dart
          - web/**.dart
      extension|client_js_copy_builder:
        enabled: true
      
builders:
  client_js_copy_builder:
    import: "tool/copy_builder.dart"
    builder_factories:
        - copyBuilder
    build_extensions:
      web/background.dart.js:
        - web/background.js
    auto_apply: none
    build_to: source
